-- This is a fixture file generated with the contents of a db dump after running the "create-assignment" test on 12/20/2025

-- The following SQL is identical to course-teacherpays.sql.

INSERT INTO "public"."User" ("id", "email", "firstName", "lastName", "createdAt", "updatedAt", "canCreateCourses", "deleted", "passwordHash", "stripeCustomerId") VALUES
('cmj9ff2w70000qr6banbe3d56', 'ta@featurebench-test.com', 'Test', 'TA', '2025-12-17 03:03:16.423', '2025-12-17 03:03:17.003', 'f', 'f', '$2b$12$H1o/8a1EWLPeI/CEPTUN3OmAscG9.9KEZO887HA9BH2ktZLf8xdUC', NULL),
('cmj9ffow70000qr6banbe3856', 'test@featurebench-test.com', 'Test', 'Teacher', '2025-12-17 03:03:16.423', '2025-12-17 03:03:17.003', 'f', 'f', '$2b$12$H1o/8a1EWLPeI/CEPTUN3OmAscG9.9KEZO887HA9BH2ktZLf8xdUC', 'cus_TdqpV2JtPv4cAL'),
('cmj9ffow70000qr6banbe3d56', 'student@featurebench-test.com', 'Test', 'Student', '2025-12-17 03:03:16.423', '2025-12-17 03:03:17.003', 'f', 'f', '$2b$12$H1o/8a1EWLPeI/CEPTUN3OmAscG9.9KEZO887HA9BH2ktZLf8xdUC', NULL);

INSERT INTO "public"."Course" ("id", "name", "abbr", "studentInviteCode", "taInviteCode", "createdAt", "updatedAt", "deleted", "billingScheme") VALUES
('cmjewhjh90000qryehjj4pkuh', 'E2E Test Course', 'E2E 222', 'STU-E2E', 'TA-E2E', '2025-12-20 22:59:27.068', '2025-12-20 22:59:27.068', 'f', 'PER_COURSE');

INSERT INTO "public"."Enrollment" ("id", "userId", "courseId", "type", "createdAt", "updatedAt", "deleted", "billingFollowUpResolvedAt") VALUES
('cmjewhjhh0002qrye2pu2vmzr', 'cmj9ffow70000qr6banbe3856', 'cmjewhjh90000qryehjj4pkuh', 'TEACHER', '2025-12-20 22:59:27.077', '2025-12-20 22:59:27.077', 'f', NULL),
('cmjewhldf0004qryeoauq050j', 'cmj9ffow70000qr6banbe3d56', 'cmjewhjh90000qryehjj4pkuh', 'STUDENT', '2025-12-20 22:59:29.524', '2025-12-20 22:59:29.524', 'f', NULL);

-- The above SQL is identical to course-teacherpays.sql.
-- The following SQL is pulled from the db.

INSERT INTO "public"."Assignment" ("id", "name", "description", "unitSystem", "pointsPossible", "gradeVisibility", "volume", "surfaceArea", "tolerancePercent", "dueDate", "createdAt", "updatedAt", "deleted", "latePolicyAllowLateSubmissions", "latePolicyInheritFromCourse", "latePolicyMaxLatenessMinutes", "latePolicyPenaltyPercent", "latePolicyPenaltyType", "courseId") VALUES
('cmjjg0nfn0001qrmbspysapdx', 'E2E Test Assignment', 'This is a test assignment, generated by and for E2E tests.', 'SI', 100, 'INSTANT', 3.006785424182888e-05, 0.01546928781003233, 0.1, '2035-12-20 05:00:00', '2025-12-24 03:17:16.067', '2025-12-24 03:17:16.067', 'f', NULL, 't', NULL, NULL, NULL, 'cmjewhjh90000qryehjj4pkuh');

INSERT INTO "public"."AssignmentSignature" ("id", "assignmentId", "sortOrder", "type", "unitSystem", "volume", "surfaceArea", "centerOfMassX", "centerOfMassY", "centerOfMassZ", "feedback", "pointsAwarded", "createdAt", "updatedAt", "deleted", "screenshotKey", "screenshotUrl") VALUES
('cmjjg0nft0002qrmbswbxinfy', 'cmjjg0nfn0001qrmbspysapdx', 1, 'CORRECT', 'SI', 3.006785424182888e-05, 0.01546928781003233, 1.738037665496153e-10, -0.005548767768492254, 0.00332351100733449, NULL, NULL, '2025-12-24 03:17:16.074', '2025-12-24 03:17:16.074', 'f', 'analyzer/prescans/screenshots/test.good-1766546231355-2573139c-a88e-46af-a3ab-04e931fd3db8.sldprt', 'https://jack-general.nyc3.digitaloceanspaces.com/analyzer/prescans/screenshots/test.good-1766546231355-2573139c-a88e-46af-a3ab-04e931fd3db8.sldprt'),
('cmjjg0nft0003qrmber7fnres', 'cmjjg0nfn0001qrmbspysapdx', 2, 'INCORRECT', 'SI', 2.990631582664338e-05, 0.01566438535520661, 1.747425647229148e-10, -0.005584063228028379, 0.003348343718129235, 'This is a test feedback', 70, '2025-12-24 03:17:16.074', '2025-12-24 03:17:16.074', 'f', 'analyzer/prescans/screenshots/test.no-chamfer-1766546235133-fb7d738e-f832-4cca-86fd-e803d1c71425.sldprt', 'https://jack-general.nyc3.digitaloceanspaces.com/analyzer/prescans/screenshots/test.no-chamfer-1766546235133-fb7d738e-f832-4cca-86fd-e803d1c71425.sldprt');

-- The following SQL is manually written to add some extra students to the course

INSERT INTO "public"."User" ("id", "email", "firstName", "lastName", "createdAt", "updatedAt", "canCreateCourses", "deleted", "passwordHash", "stripeCustomerId") VALUES
('cmj9ffow70000qr6bagbe3d51', 'student1@featurebench-test.com', 'Test', 'Student 1', '2025-12-17 03:03:16.423', '2025-12-17 03:03:17.003', 'f', 'f', '$2b$12$H1o/8a1EWLPeI/CEPTUN3OmAscG9.9KEZO887HA9BH2ktZLf8xdUC', NULL);
('cmj9ffow70000qr6bagbe3d52', 'student2@featurebench-test.com', 'Test', 'Student 2', '2025-12-17 03:03:16.423', '2025-12-17 03:03:17.003', 'f', 'f', '$2b$12$H1o/8a1EWLPeI/CEPTUN3OmAscG9.9KEZO887HA9BH2ktZLf8xdUC', NULL);
('cmj9ffow70000qr6bagbe3d53', 'student3@featurebench-test.com', 'Test', 'Student 3', '2025-12-17 03:03:16.423', '2025-12-17 03:03:17.003', 'f', 'f', '$2b$12$H1o/8a1EWLPeI/CEPTUN3OmAscG9.9KEZO887HA9BH2ktZLf8xdUC', NULL);
('cmj9ffow70000qr6bagbe3d54', 'student4@featurebench-test.com', 'Test', 'Student 4', '2025-12-17 03:03:16.423', '2025-12-17 03:03:17.003', 'f', 'f', '$2b$12$H1o/8a1EWLPeI/CEPTUN3OmAscG9.9KEZO887HA9BH2ktZLf8xdUC', NULL);

INSERT INTO "public"."Enrollment" ("id", "userId", "courseId", "type", "createdAt", "updatedAt", "deleted", "billingFollowUpResolvedAt") VALUES
('cmjewhjhh00302qrye2pu2mzr', 'cmj9ffow70000qr6bagbe3d51', 'cmjewhjh90000qryehjj4pkuh', 'STUDENT', '2025-12-20 22:59:27.077', '2025-12-20 22:59:27.077', 'f', NULL),
('cmjewhjhh00302qrye7pu2mzr', 'cmj9ffow70000qr6bagbe3d52', 'cmjewhjh90000qryehjj4pkuh', 'STUDENT', '2025-12-20 22:59:27.077', '2025-12-20 22:59:27.077', 'f', NULL),
('cmjewhjhh003k2qrye2pu2mzr', 'cmj9ffow70000qr6bagbe3d53', 'cmjewhjh90000qryehjj4pkuh', 'STUDENT', '2025-12-20 22:59:27.077', '2025-12-20 22:59:27.077', 'f', NULL),
('cmjewrjhh00302qrye2pu2mzr', 'cmj9ffow70000qr6bagbe3d54', 'cmjewhjh90000qryehjj4pkuh', 'STUDENT', '2025-12-20 22:59:27.077', '2025-12-20 22:59:27.077', 'f', NULL),
