-- This is a fixture file generated by dumping the db after running the test "create-course-teacher-pays" on 12/20/2025

INSERT INTO "public"."User" ("id", "email", "firstName", "lastName", "createdAt", "updatedAt", "canCreateCourses", "deleted", "passwordHash", "stripeCustomerId") VALUES
('cmj9ff2w70000qr6banbe3d56', 'ta@featurebench-test.com', 'Test', 'TA', '2025-12-17 03:03:16.423', '2025-12-17 03:03:17.003', 'f', 'f', '$2b$12$H1o/8a1EWLPeI/CEPTUN3OmAscG9.9KEZO887HA9BH2ktZLf8xdUC', NULL),
('cmj9ffow70000qr6banbe3856', 'test@featurebench-test.com', 'Test', 'Teacher', '2025-12-17 03:03:16.423', '2025-12-17 03:03:17.003', 'f', 'f', '$2b$12$H1o/8a1EWLPeI/CEPTUN3OmAscG9.9KEZO887HA9BH2ktZLf8xdUC', 'cus_TdqpV2JtPv4cAL'),
('cmj9ffow70000qr6banbe3d56', 'student@featurebench-test.com', 'Test', 'Student', '2025-12-17 03:03:16.423', '2025-12-17 03:03:17.003', 'f', 'f', '$2b$12$H1o/8a1EWLPeI/CEPTUN3OmAscG9.9KEZO887HA9BH2ktZLf8xdUC', NULL);

INSERT INTO "public"."Course" ("id", "name", "abbr", "studentInviteCode", "taInviteCode", "createdAt", "updatedAt", "deleted", "billingScheme") VALUES
('cmjewhjh90000qryehjj4pkuh', 'E2E Test Course', 'E2E 222', 'STU-E2E', 'TA-E2E', '2025-12-20 22:59:27.068', '2025-12-20 22:59:27.068', 'f', 'PER_COURSE');

INSERT INTO "public"."Enrollment" ("id", "userId", "courseId", "type", "createdAt", "updatedAt", "deleted", "billingFollowUpResolvedAt") VALUES
('cmjewhjhh0002qrye2pu2vmzr', 'cmj9ffow70000qr6banbe3856', 'cmjewhjh90000qryehjj4pkuh', 'TEACHER', '2025-12-20 22:59:27.077', '2025-12-20 22:59:27.077', 'f', NULL),
('cmjewhldf0004qryeoauq050j', 'cmj9ffow70000qr6banbe3d56', 'cmjewhjh90000qryehjj4pkuh', 'STUDENT', '2025-12-20 22:59:29.524', '2025-12-20 22:59:29.524', 'f', NULL);

-- The above code is depended on by the following fixtures.
--   - course-tp-assignment.sql